Add Bicep Support and easy setup.sh script for deployment
Azure/notation-azure-kv pull request #17
Opened 2022-04-27 23:11 UTC by jldeen

- Adds support to deploy all resources using Azure Bicep
- Adds support to call `./setup.sh` script for quick and easy deployment / signing of container images using Gatekeeper, Ratify, and Notation

2022-04-27 23:34 UTC, dtzar requested changes

2022-04-27 23:34 UTC, dtzar commented on docs/nv2-bicep.md
> +2. ~~Add createSigningCertforKv Function~~
Looks like you have added these functions...

2022-04-27 23:34 UTC, dtzar commented on docs/nv2-bicep.md
> +
Now that the script executes [all of the flow](https://github.com/Azure/notation-azure-kv/pull/17/files#diff-4209d788ad32c40cbda3c66b3de47eefb929308ca703bb77a6382625986add17R345-R353) you've got nothing really to *show* or explain.  

I suggest you break out the buildImageandSign functions so you can explain/show them (versus auto execution) or at a bare minimum put some text in here to have the user see the signed image.

2022-04-27 23:35 UTC, dtzar commented
@jldeen Thanks for this PR!  A couple tweaks and I'll go ahead and merge this.

2022-05-05 22:09 UTC, jldeen commented
@dtzar Apologies for the delay, please see latest changes and let me know if there are other updates I should add. Thank you!

2022-05-19 20:00 UTC, dtzar approved these changes

2022-05-19 20:00 UTC, merged

2022-05-19 20:01 UTC, dtzar commented
Thank you for your work on this @jldeen!